<?php

include('../../../../wp-config.php');
global $wpdb;


$uploadedfile = $_FILES['filee'];
$file_name = $uploadedfile['name'];
$file_extent = explode(".",$file_name);
$endd = end($file_extent); 

if ( ! function_exists( 'wp_handle_upload' ) ) {
   require_once( ABSPATH . 'wp-admin/includes/file.php' );
}


$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
echo $img_url = $movefile[url];
if ( $movefile && !isset( $movefile['error'] ) ) {
   "File is valid, and was successfully uploaded.\n";
  echo $file_check=var_dump( $movefile);
echo $img_url = $movefile[url];
} else {
   /**
    * Error generated by _wp_handle_upload()
    * @see _wp_handle_upload() in wp-admin/includes/file.php
    */
  echo $movefile['error'];
}
$fname = $_POST['firstname'];
$lname = $_POST['lastname'];
$phone = $_POST['phone'];
$email = $_POST['email'];
$option1 = $_POST['contact1'];

$option2 = $_POST['contact2'];
$msg1 = $_POST['msg'];

// $file = $_POST['filee'];
 $admin_email = get_option( 'admin_email' ); 
// $admin_email = "steelcorbldgs@gmail.com"; 
$client1 = get_field('client_email1',5); 
// echo"$client1";

// $client2 = get_field('client_email2',5);
// echo"$client2";
require_once ABSPATH.'wp-content/themes/hanger-steel/mailer/class.phpmailer.php';

$mail = new PHPMailer(true); //defaults to using php "mail()"; the true param means it will throw exceptions on errors, which we need to catch

try
{
  $mail->AddReplyTo('caquesinberry@aol.com', 'Hangar Steel');
  $mail->AddAddress($admin_email);
   $mail->AddAddress($client1);
  // $mail->AddAddress($client2);
  $mail->SetFrom('nadia.kaloyanova@gmail.com', 'Hangar Steel');
  $mail->Subject = 'Architect';
  $mail->AltBody = 'To view the message, please use an HTML compatible email viewer!'; // optional - MsgHTML will create an alternate automatically
  $file=ABSPATH.'wp-content/themes/hanger-steel/ajax/admin-mail/admin-mail-architect.html';
  $emailBody = file_get_contents($file);
	$search  = array('[[fname]]', '[[lname]]', '[[phone]]', '[[email]]','[[option1]]','[[option2]]','[[img_url]]','[[msg1]]');
	$replace = array($fname, $lname,$phone,$email,$option1,$option2,$img_url,$msg1); 
	
	$emailBody  = str_replace($search, $replace, $emailBody);
  $mail->MsgHTML( $emailBody );
 
  $mail->Send();
  //echo "Message Sent OK</p>\n";
} 
catch (phpmailerException $e) 
{
  echo $e->errorMessage(); //Pretty error messages from PHPMailer
} catch (Exception $e) 
{
  echo $e->getMessage(); //Boring error messages from anything else!
}
echo "1";

?>