<?php

include('../../../../wp-config.php');
global $wpdb;

$uploadedfile = $_FILES['filee'];
if ( ! function_exists( 'wp_handle_upload' ) ) {
   require_once( ABSPATH . 'wp-admin/includes/file.php' );
}


$upload_overrides = array( 'test_form' => false );

$movefile = wp_handle_upload( $uploadedfile, $upload_overrides );
echo $img_url = $movefile[url];
if ( $movefile && !isset( $movefile['error'] ) ) {
   "File is valid, and was successfully uploaded.\n";
  echo $file_check=var_dump( $movefile);
echo $img_url = $movefile[url];
} else {
   /**
    * Error generated by _wp_handle_upload()
    * @see _wp_handle_upload() in wp-admin/includes/file.php
    */
  echo $movefile['error'];
}
$name = $_POST['name'];
$com = $_POST['company'];
$add = $_POST['address'];
$email2 = $_POST['email1'];
$Pphone = $_POST['pphone'];
$Sphone = $_POST['sphone'];
$apt = $_POST['as'];
$city1 = $_POST['city'];
$state1 = $_POST['state'];
$zc1 = $_POST['zc'];
$option1 = $_POST['contact1'];
$amm1 = $_POST['amm'];
$wid1 = $_POST['wid'];
$dpt1 = $_POST['dpt'];
$he1 = $_POST['he'];
$dh1 = $_POST['dh'];
$dw1 = $_POST['dw'];
$option2 = $_POST['contact2'];
$option3 = $_POST['contact3'];
$msg1 = $_POST['msg'];
// $file = $_POST['uploaded'];
$admin_email = get_option( 'admin_email' ); 
// $admin_email = "steelcorbldgs@gmail.com"; 
$client1 = get_field('client_email1',5); 
// echo"$client1";

// $client2 = get_field('client_email2',5);
// echo"$client2";
require_once ABSPATH.'wp-content/themes/hanger-steel/mailer/class.phpmailer.php';

$mail = new PHPMailer(true); //defaults to using php "mail()"; the true param means it will throw exceptions on errors, which we need to catch

try
{
   $mail->AddReplyTo('caquesinberry@aol.com', 'Hangar Steel');
   $mail->AddAddress($admin_email);
   $mail->AddAddress($client1);
  // $mail->AddAddress($client2);
  $mail->SetFrom('nadia.kaloyanova@gmail.com', 'Hangar Steel');
  $mail->Subject = 'Quote Price';
  $mail->AltBody = 'To view the message, please use an HTML compatible email viewer!'; // optional - MsgHTML will create an alternate automatically
  $file=ABSPATH.'wp-content/themes/hanger-steel/ajax/admin-mail/admin-mail-quote.html';
  $emailBody = file_get_contents($file);
	$search  = array('[[name]]', '[[com]]', '[[add]]', '[[email2]]','[[Pphone]]','[[Sphone]]','[[apt]]','[[city1]]','[[state1]]','[[zc1]]','[[option1]]','[[amm1]]','[[wid1]]','[[dpt1]]','[[he1]]','[[dh1]]','[[dw1]]','[[option2]]','[[option3]]','[[img_url]]','[[msg1]]');
	$replace = array($name, $com, $add, $email2, $Pphone, $Sphone, $apt, $city1, $state1, $zc1, $option1, $amm1, $wid1, $dpt1, $he1, $dh1, $dw1, $option2, $option3, $img_url,$msg1); 
	
	$emailBody  = str_replace($search, $replace, $emailBody);
  $mail->MsgHTML( $emailBody );
 
  $mail->Send();
  //echo "Message Sent OK</p>\n";
} 
catch (phpmailerException $e) 
{
  echo $e->errorMessage(); //Pretty error messages from PHPMailer
} catch (Exception $e) 
{
  echo $e->getMessage(); //Boring error messages from anything else!
}


?>